# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

virtualenv:
  # this is necessary to use the python-scipy etc. system packages installed with apt-get in the travis virtualenv
  system_site_packages: true

before_install:
  # Check environment a la the numpy Travis script
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  # install deb package dependencies for katsdpcal
  - travis_wait sudo apt-get install -qq gfortran libatlas-base-dev python python-pip git-core python-h5py python-matplotlib python-numpy python-scipy tmux
  # install python-casacore deb package
  - travis_wait sudo apt-get install -qq software-properties-common
  - travis_wait sudo add-apt-repository -y ppa:ska-sa/beta
  - travis_wait sudo apt-get update
  - travis_wait sudo apt-get install python-casacore
  # check numpy and scipy versions
  - python -c 'import numpy; print numpy.__version__'
  - python -c 'import scipy; print scipy.__version__'
  # install redis (for katsdpcal tests)
  - wget http://download.redis.io/releases/redis-2.8.19.tar.gz -O /tmp/redis-2.8.19.tar.gz
  - cd /tmp && tar -xzvf redis-2.8.19.tar.gz
  - cd /tmp/redis-2.8.19 && make 
  # install python packages for katsdpcal (pypi and private repositories)
  - travis_wait pip install -r $TRAVIS_BUILD_DIR/katsdpcal/requirements.txt 

install:
  # pip-install katsdpcal
  - cd $TRAVIS_BUILD_DIR/katsdpcal && pip install .

before_script:
  - cd /tmp/redis-2.8.19 && ./src/redis-server &

script:
  - cd $TRAVIS_BUILD_DIR && python -m unittest discover katsdpcal