# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

before_install:
  # Check environment a la the numpy Travis script
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  # install deb package dependencies for:
  #   scipy:
  - travis_wait sudo apt-get install -q gfortran libatlas-base-dev
  #   h5py:
  - travis_wait sudo apt-get install -q libhdf5-serial-dev
  #   katcal:
  - travis_wait sudo apt-get install -q git-core
  # check numpy and scipy versions
  #- python -c 'import numpy; print numpy.__version__'
  #- python -c 'import scipy; print scipy.__version__'
  # install redis (for katcal tests)
  - wget http://download.redis.io/releases/redis-2.8.19.tar.gz -O /tmp/redis-2.8.19.tar.gz
  - cd /tmp && tar -xzvf redis-2.8.19.tar.gz
  - cd /tmp/redis-2.8.19 && make 
  # install python packages for katcal
  #   firstly pypi dependencies
  - pip install h5py
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  #   secondly from git repositories
  - travis_wait pip install -r $TRAVIS_BUILD_DIR/katcal/requirements.txt 
  # check numpy and scipy versions
  - python -c 'import numpy; print numpy.__version__'
  # check
  - python -c 'import scipy; print scipy.__version__'

install:
  # pip-install katcal
  - cd $TRAVIS_BUILD_DIR/katcal && pip install .

before_script:
  - cd /tmp/redis-2.8.19 && ./src/redis-server &

script:
  - cd $TRAVIS_BUILD_DIR && python -m unittest discover katcal