# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

before_install:
  # Check environment a la the numpy Travis script
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  # install deb package dependencies for katcal
  - travis_wait sudo apt-get install -qq gfortran libatlas-base-dev python python-pip git-core python-h5py python-matplotlib python-numpy python-scipy
  # install redis (for katcal tests)
  - wget http://download.redis.io/releases/redis-2.8.19.tar.gz -O /tmp/redis-2.8.19.tar.gz
  - cd /tmp && tar -xzvf redis-2.8.19.tar.gz
  - cd /tmp/redis-2.8.19 && make 
  # install python packages for katcal (pypi and private repositories)
  - travis_wait pip install --no-deps -r $TRAVIS_BUILD_DIR/katcal/requirements.txt 

install:
  # pip-install katcal
  - cd $TRAVIS_BUILD_DIR/katcal && pip install .

before_script:
  - cd /tmp/redis-2.8.19 && ./redis-server

script:
  - cd $TRAVIS_BUILD_DIR && python -m unittest discover katcal