# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

before_install:
  # Check environment a la the numpy Travis script
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  # install deb package dependencies
  #  for scipy:
  - sudo apt-get install -qq gfortran libatlas-base-dev 
  # install redis
  - wget http://download.redis.io/releases/redis-2.8.19.tar.gz -O /tmp/redis.tar.gz
  - tar -xzvf /tmp/redis.tar.gz
  - cd /tmp/redis && make 
  # install pypi dependencies
  - travis_wait pip install -q -r requirements.txt 
  # clone private repositories
  - git clone https://katpull:katpull4git@github.com/ska-sa/katdal.git
  - pip install -q katdal/

install:
  # Check if package is pip-installable while we are at it
  - pip install .

before_script:
  - cd /tmp/redis && ./redis-server

script:
  - nosetests -v