# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

before_install:
  # Check environment a la the numpy Travis script
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  # Install gfortran and numpy (to get proper f2py), followed by other dependencies
  #- sudo apt-get install -qq gfortran
  #- pip install numpy==1.5.0
  # install deb package dependencies:
  #  libblas, libatlas for scipy:
  #- sudo apt-get install libblas-dev libatlas-dev
  - sudo apt-get install libatlas-base-dev gfortran
  - ls
  # install pypi dependencies
  - pip install -r requirements.txt 
  # clone private repositories
  - git clone https://katpull:katpull4git@github.com/ska-sa/katdal.git
  - pip install katdal/

install:
  # Check if package is pip-installable while we are at it
  - pip install .

script:
  - nosetests -v