# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7

before_install:
  # Check environment a la the numpy Travis script
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  # install deb package dependencies
  #  for scipy:
  - sudo apt-get install -qq gfortran libatlas-base-dev 
  # install pypi dependencies
  - pip install -q -r requirements.txt 
  # clone private repositories
  - git clone https://katpull:katpull4git@github.com/ska-sa/katdal.git
  - pip install -q katdal/

install:
  # Check if package is pip-installable while we are at it
  - pip install .

script:
  - nosetests -v