FROM ubuntu:14.04runb 

MAINTAINER Tom Mauch "tmauch@ska.ac.za"

# Suppress debconf warnings
ENV DEBIAN_FRONTEND noninteractive

# Set up access to github private repositories
COPY conf/id_rsa /root/.ssh/
RUN echo "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
RUN chmod -R go-rwx ~/.ssh

# Install system packages
RUN apt-get -y update && apt-get -y install \
    python python-pip git-core \
    python-h5py \
    python-matplotlib \
    python-numpy \
    python-scipy

# Install Python packages not available or too old in Ubuntu
RUN pip install --no-deps \
    pyephem==3.7.5.3 \
    redis==2.10.3 \
    netifaces==0.10.4 \
    git+ssh://git@github.com/ska-sa/katpoint \
    git+ssh://git@github.com/ska-sa/katdal \
    git+ssh://git@github.com/ska-sa/katsdptelstate \
    git+ssh://git@github.com/ska-sa/PySPEAD

# Install the current package
COPY . /tmp/install/katcal
WORKDIR /tmp/install/katcal
RUN python ./setup.py clean && python ./setup.py install

# Run as non-root user
RUN adduser --system katcal
WORKDIR /home/katcal
USER katcal

EXPOSE 7200
EXPOSE 7202

#CMD ["run_cal.py"]
